name = "hono-todo-api"
main = "src/index.ts"
compatibility_date = "2024-11-20"

# compatibility_flags = [ "nodejs_compat" ]

#[[d1_databases]]
#binding = ""
#database_name = ""
#database_id = ""
#migrations_dir = "drizzle/migrations"
